services:
  redis:
    image: redis:8.6.3
    container_name: redis
    ports:
      - '127.0.0.1:3030:6379'
    volumes:
      - ./files/redis:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]
    restart: unless-stopped

  spectra-frontend:
    image: local-spectra:latest
    ports:
      - "3200:80"
    volumes:
      - ./files/spectra-frontend/config:/usr/share/nginx/html/assets/config/